# Repository labels configuration
labels:
  # Type labels
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: feature
    color: a2eeef
    description: New feature or request
  - name: enhancement
    color: 84b6eb
    description: Enhancement to existing feature
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  # Area labels  
  - name: frontend
    color: 1d76db
    description: Frontend/Client related changes
  - name: backend
    color: 5319e7
    description: Backend/Server related changes
  - name: database
    color: 0e8a16
    description: Database related changes
  - name: api
    color: 7057ff
    description: API related changes
  - name: ui/ux
    color: e99695
    description: User interface and experience

  # Component labels
  - name: authentication
    color: 006b75
    description: Authentication and authorization
  - name: events
    color: 0052cc
    description: Events functionality
  - name: athletes
    color: 5319e7
    description: Athletes functionality  
  - name: community
    color: 0e8a16
    description: Community features
  - name: venues
    color: fbca04
    description: Venues functionality
  - name: leaderboard
    color: d876e3
    description: Leaderboard features
  - name: notifications
    color: c5def5
    description: Notifications system

  # Priority labels
  - name: priority/critical
    color: b60205
    description: Critical priority
  - name: priority/high
    color: d93f0b
    description: High priority
  - name: priority/medium
    color: fbca04
    description: Medium priority
  - name: priority/low
    color: 0e8a16
    description: Low priority

  # Size labels
  - name: 'size/XS'
    color: ededed
    description: Extra Small (≤ 10 lines)
  - name: 'size/S'
    color: c5def5
    description: Small (≤ 50 lines)
  - name: 'size/M'
    color: bfdadc
    description: Medium (≤ 150 lines)
  - name: 'size/L'
    color: f9d0c4
    description: Large (≤ 300 lines)
  - name: 'size/XL'
    color: f7c6c7
    description: Extra Large (> 300 lines)

  # Status labels
  - name: 'good first issue'
    color: 7057ff
    description: Good for newcomers
  - name: 'help wanted'
    color: 008672
    description: Extra attention is needed
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: stale
    color: fef2c0
    description: No recent activity

  # Special labels
  - name: security
    color: b60205
    description: Security related
  - name: performance
    color: fef2c0
    description: Performance related
  - name: testing
    color: 6f42c1
    description: Testing related
  - name: ci/cd
    color: 0366d6
    description: CI/CD related