# Release Drafter configuration
name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'build'
      - 'ci'
      - 'refactor'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
  default: patch

template: |
  ## What's Changed 🎉
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ## Contributors 🙏
  
  Thanks to all contributors who made this release possible!